# Variables
@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.acess_token}}

GET {{baseUrl}}/api/hello

###

POST {{baseUrl}}/accounts
Accept: application/json
Content-Type: application/json

{
  "name": "Thallys",
  "email": "thallys2@hotmail.com",
  "password": "123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "thallys2@hotmail.com",
  "password": "123"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}